"use client";

import { type FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Boxes, CalendarClock, CircleDollarSign, ClipboardList, PackageCheck, Plus, RefreshCw, Search, Truck, Warehouse, X } from "lucide-react";
import { Badge, Card, Stat } from "@/components/ui/core";

type MaterialStatus = "needed" | "order_today" | "ordered" | "delivered" | "backordered" | "cancelled";
type MaterialItem = { id: string; project_id: string; article_number: string | null; name: string; quantity: number | string; unit: string; needed_on: string | null; preferred_supplier: string | null; unit_price: number | string; status: MaterialStatus; stock_note: string | null; created_at: string; updated_at: string };
type Offer = { id: string; material_item_id: string; supplier_name: string; total_price: number | string; delivery_at: string | null; delivery_note: string | null; availability: string | null; recommended: boolean; valid_until: string | null; created_at: string };
type Order = { id: string; project_id: string; order_number: string; supplier_name: string; status: string; total_amount: number | string; approved_at: string | null; ordered_at: string | null; created_at: string; updated_at: string };
type Delivery = { id: string; purchase_order_id: string; project_id: string; status: string; scheduled_at: string | null; delivered_at: string | null; note: string | null; updated_at: string };
type Project = { id: string; code: string; name: string; status: string; updated_at: string };
type OrderListItem = { id: string; material_order_list_id: string; catalog_product_id: string; merchant_product_id: string | null; selected_store_id: string | null; quantity: number | string; unit: string; stock_status_at_selection: string | null; stock_checked_at: string | null; selected_price_source: string | null; selected_unit_cost_ex_vat: number | string | null; shelf_price_ex_vat: number | string | null; customer_unit_price_ex_vat: number | string | null; updated_at: string };
type CatalogProduct = { id: string; name: string; manufacturer: string | null; manufacturer_article_number: string | null; base_unit: string; updated_at: string };
type OwnPrice = { id: string; catalog_product_id: string; latest_invoice_price_ex_vat: number | string | null; latest_invoice_unit: string | null; latest_invoice_date: string | null; manual_cost_price_ex_vat: number | string | null; manual_cost_unit: string | null; updated_at: string };
type PriceList = { id: string; name: string; source_type: string; status: string; currency: string; imported_at: string | null; updated_at: string };
type PriceListItem = { id: string; price_list_id: string; catalog_product_id: string | null; merchant_product_id: string | null; supplier_article_number: string; supplier_description: string | null; contract_price_ex_vat: number | string; price_unit: string; valid_from: string | null; valid_until: string | null; updated_at: string };
type ShelfPrice = { id: number | string; merchant_product_id: string; store_id: string | null; price_ex_vat: number | string; price_inc_vat: number | string; currency: string; price_unit: string; valid_from: string; valid_to: string | null; observed_at: string; last_verified_at: string; source_reference: string };
type Inventory = { id: number | string; merchant_product_id: string; store_id: string; stock_status: string; quantity_available: number | string | null; quantity_unit: string | null; pickup_available: boolean | null; delivery_available: boolean | null; lead_time_days: number | null; captured_at: string; expires_at: string; source_reference: string };
type Calculation = { id: string; material_order_list_item_id: string; algorithm_version: string; status: string; baseline_stop_hours: number | string; recommended_option_id: string | null; calculation_summary: string | null; calculated_at: string | null; created_at: string };
type FulfillmentOption = { id: string; calculation_id: string; store_id: string | null; fulfillment_method: string; stock_status: string; unit_price_ex_vat: number | string | null; material_cost_ex_vat: number | string; lead_time_hours: number | string; estimated_stop_hours: number | string; downtime_cost: number | string; schedule_risk_cost: number | string; total_effective_cost: number | string | null; downtime_avoided_value: number | string; recommended: boolean; reason: string | null; price_checked_at: string | null; stock_checked_at: string | null; created_at: string };
type Store = { id: string; name: string; city: string | null; store_url: string | null; last_verified_at: string | null; updated_at: string };
type Payload = { items: MaterialItem[]; offers: Offer[]; orders: Order[]; deliveries: Delivery[]; projects: Project[]; orderListItems: OrderListItem[]; ownPrices: OwnPrice[]; priceLists: PriceList[]; priceListItems: PriceListItem[]; calculations: Calculation[]; options: FulfillmentOption[]; downtimeProfiles: Array<{ id: string; name: string; updated_at: string }>; catalogProducts: CatalogProduct[]; shelfPrices: ShelfPrice[]; inventory: Inventory[]; stores: Store[]; permissions: { canManage: boolean }; fetchedAt: string };

const statusLabels: Record<MaterialStatus, string> = { needed: "Behövs", order_today: "Beställ idag", ordered: "Beställd", delivered: "Levererad", backordered: "Restnoterad", cancelled: "Avbruten" };
const statusOptions = Object.keys(statusLabels) as MaterialStatus[];
const money = new Intl.NumberFormat("sv-SE", { style: "currency", currency: "SEK" });
const number = new Intl.NumberFormat("sv-SE", { maximumFractionDigits: 3 });
const date = new Intl.DateTimeFormat("sv-SE", { dateStyle: "medium" });
const dateTime = new Intl.DateTimeFormat("sv-SE", { dateStyle: "medium", timeStyle: "short" });
const emptyPayload: Payload = { items: [], offers: [], orders: [], deliveries: [], projects: [], orderListItems: [], ownPrices: [], priceLists: [], priceListItems: [], calculations: [], options: [], downtimeProfiles: [], catalogProducts: [], shelfPrices: [], inventory: [], stores: [], permissions: { canManage: false }, fetchedAt: "" };

function formatDate(value: string | null) { return value ? date.format(new Date(`${value.slice(0, 10)}T12:00:00`)) : "Ej angivet"; }
function formatDateTime(value: string | null) { return value ? dateTime.format(new Date(value)) : "Ej angivet"; }
function amount(value: number | string | null) { const parsed = value === null ? Number.NaN : Number(value); return Number.isFinite(parsed) ? money.format(parsed) : "Ej registrerat"; }
function tone(status: MaterialStatus) { return status === "delivered" ? "success" as const : ["order_today", "backordered"].includes(status) ? "warning" as const : "neutral" as const; }

export default function LiveMaterialsModule({ notify }: { notify: (message: string) => void }) {
  const [data, setData] = useState<Payload>(emptyPayload);
  const [tab, setTab] = useState<"materials" | "orders" | "prices">("materials");
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [formOpen, setFormOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    const response = await fetch("/api/private/materials", { cache: "no-store" });
    const payload = await response.json().catch(() => null);
    if (!response.ok) setError(payload?.error ?? "Materialuppgifterna kunde inte hämtas.");
    else { setData(payload as Payload); setError(null); }
    setLoading(false);
  }, []);

  useEffect(() => { const frame = window.requestAnimationFrame(() => void load()); return () => window.cancelAnimationFrame(frame); }, [load]);

  const projects = useMemo(() => new Map(data.projects.map((project) => [project.id, project])), [data.projects]);
  const products = useMemo(() => new Map(data.catalogProducts.map((product) => [product.id, product])), [data.catalogProducts]);
  const stores = useMemo(() => new Map(data.stores.map((store) => [store.id, store])), [data.stores]);
  const search = query.trim().toLowerCase();
  const visibleItems = data.items.filter((item) => !search || [item.name, item.article_number, item.preferred_supplier, projects.get(item.project_id)?.name].some((value) => value?.toLowerCase().includes(search)));
  const visibleOrders = data.orders.filter((order) => !search || [order.order_number, order.supplier_name, projects.get(order.project_id)?.name].some((value) => value?.toLowerCase().includes(search)));
  const activeOrders = data.orders.filter((order) => !["delivered", "cancelled"].includes(order.status));
  const incomingDeliveries = data.deliveries.filter((delivery) => !["delivered", "rejected"].includes(delivery.status));
  const knownMaterialTotal = data.items.reduce((sum, item) => sum + Number(item.quantity) * Number(item.unit_price), 0);

  async function createItem(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true);
    const response = await fetch("/api/private/materials", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) });
    const payload = await response.json().catch(() => null);
    if (!response.ok) setError(payload?.error ?? "Materialposten kunde inte sparas.");
    else { notify("Materialposten registrerades"); setFormOpen(false); setError(null); await load(); }
    setSaving(false);
  }

  async function updateStatus(id: string, status: MaterialStatus) {
    const response = await fetch("/api/private/materials", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status }) });
    const payload = await response.json().catch(() => null);
    if (!response.ok) setError(payload?.error ?? "Materialstatusen kunde inte uppdateras.");
    else { notify("Materialstatusen uppdaterades"); await load(); }
  }

  return <div className="space-y-5">
    <Card className="flex flex-col justify-between gap-6 bg-zinc-950 p-7 text-white xl:flex-row xl:items-end">
      <div><Badge tone="success">Live från Supabase</Badge><h2 className="mt-5 text-4xl font-semibold tracking-tight">Material & inköp</h2><p className="mt-3 max-w-3xl text-zinc-300">Material, leverantörsofferter, order, leveranser och verifierade pris-/lagersnapshots för det aktiva företaget.</p><p className="mt-4 text-xs text-zinc-400">{data.fetchedAt ? `Hämtat ${formatDateTime(data.fetchedAt)}.` : "Väntar på live-data."} Pris och lager visas med källans egen kontrolltid.</p></div>
      <div className="flex flex-wrap gap-2"><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-2xl border border-white/20 px-4 py-3 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} /> Uppdatera</button>{data.permissions.canManage && <button onClick={() => setFormOpen(true)} className="inline-flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm font-semibold text-zinc-950"><Plus className="h-4 w-4" /> Registrera material</button>}</div>
    </Card>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={ClipboardList} label="Öppna materialposter" value={String(data.items.filter((item) => !["delivered", "cancelled"].includes(item.status)).length)} helper="Verkliga registrerade poster" /><Stat icon={CircleDollarSign} label="Registrerat materialvärde" value={money.format(knownMaterialTotal)} helper="Mängd × registrerat enhetspris" /><Stat icon={PackageCheck} label="Aktiva inköpsorder" value={String(activeOrders.length)} helper="Ej levererade eller avbrutna" /><Stat icon={Truck} label="Kommande leveranser" value={String(incomingDeliveries.length)} helper="Schemalagda, på väg eller delvisa" /></div>
    {error && <p className="rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}

    {formOpen && <Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Registrera verklig materialpost</h3><p className="mt-1 text-sm text-zinc-500">Enhetspriset måste komma från ett faktiskt underlag; lagertext är valfri och märks som manuell.</p></div><button onClick={() => setFormOpen(false)} aria-label="Stäng"><X className="h-5 w-5" /></button></div><form onSubmit={createItem} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select name="projectId" required className="rounded-2xl border border-zinc-200 px-4 py-3 text-sm"><option value="">Välj projekt</option>{data.projects.map((project) => <option key={project.id} value={project.id}>{project.code} · {project.name}</option>)}</select><input name="name" required maxLength={240} placeholder="Materialnamn" className="rounded-2xl border border-zinc-200 px-4 py-3 text-sm" /><input name="articleNumber" maxLength={120} placeholder="Artikelnummer (valfritt)" className="rounded-2xl border border-zinc-200 px-4 py-3 text-sm" /><input name="quantity" required type="number" min="0" step="0.001" placeholder="Mängd" className="rounded-2xl border border-zinc-200 px-4 py-3 text-sm" /><input name="unit" required maxLength={24} placeholder="Enhet" className="rounded-2xl border border-zinc-200 px-4 py-3 text-sm" /><input name="unitPrice" required type="number" min="0" step="0.01" placeholder="Enhetspris kr" className="rounded-2xl border border-zinc-200 px-4 py-3 text-sm" /><label className="rounded-2xl border border-zinc-200 px-4 py-2 text-xs text-zinc-500">Behövs datum<input name="neededOn" type="date" className="mt-1 block w-full text-sm text-zinc-950 outline-none" /></label><input name="preferredSupplier" maxLength={180} placeholder="Föredragen leverantör (valfri)" className="rounded-2xl border border-zinc-200 px-4 py-3 text-sm" /><input name="stockNote" maxLength={500} placeholder="Manuell lageranteckning (valfri)" className="rounded-2xl border border-zinc-200 px-4 py-3 text-sm" /><button disabled={saving || !data.projects.length} className="rounded-2xl bg-zinc-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Sparar…" : "Spara"}</button></form>{!data.projects.length && <p className="mt-3 text-sm text-amber-700">Ett verkligt projekt krävs innan material kan registreras.</p>}</Card>}

    <Card className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="inline-flex w-fit rounded-2xl bg-zinc-100 p-1">{(["materials", "orders", "prices"] as const).map((value) => <button key={value} onClick={() => setTab(value)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab === value ? "bg-white shadow-sm" : "text-zinc-500"}`}>{value === "materials" ? "Material" : value === "orders" ? "Order & leverans" : "Pris, lager & stillestånd"}</button>)}</div><label className="flex w-full items-center gap-3 rounded-2xl border border-zinc-200 px-4 py-3 lg:max-w-md"><Search className="h-5 w-5 text-zinc-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Sök material, projekt eller leverantör" className="w-full bg-transparent text-sm outline-none" /></label></div>

      {loading ? <p className="p-12 text-center text-zinc-500">Hämtar materialdata…</p> : tab === "materials" ? <div className="mt-5 space-y-3">{!visibleItems.length ? <Empty icon={Boxes} title={data.items.length ? "Inga materialposter matchar sökningen." : "Inga materialposter är registrerade."} text="Inga behov, priser eller lageruppgifter visas utan lagrad data." /> : visibleItems.map((item) => { const offers = data.offers.filter((offer) => offer.material_item_id === item.id); return <article key={item.id} className="rounded-2xl border border-zinc-200 p-4"><div className="flex flex-col gap-4 xl:flex-row xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{item.name}</h3><Badge tone={tone(item.status)}>{statusLabels[item.status]}</Badge></div><p className="mt-2 text-sm text-zinc-600">{number.format(Number(item.quantity))} {item.unit} · {projects.get(item.project_id)?.name ?? "Okänt projekt"}{item.article_number ? ` · ${item.article_number}` : ""}</p><p className="mt-2 text-xs text-zinc-400">Behövs {formatDate(item.needed_on)} · Materialpostens enhetspris {amount(item.unit_price)} · Uppdaterad {formatDateTime(item.updated_at)}</p>{item.stock_note && <p className="mt-2 text-xs text-amber-700">Manuell lageranteckning: {item.stock_note}</p>}</div>{data.permissions.canManage && <select value={item.status} onChange={(event) => void updateStatus(item.id, event.target.value as MaterialStatus)} className="h-fit rounded-xl border border-zinc-200 px-3 py-2 text-sm">{statusOptions.map((status) => <option key={status} value={status}>{statusLabels[status]}</option>)}</select>}</div>{offers.length > 0 && <div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{offers.map((offer) => <div key={offer.id} className="rounded-2xl bg-zinc-50 p-3 text-sm"><div className="flex justify-between gap-2"><span className="font-semibold">{offer.supplier_name}</span>{offer.recommended && <Badge tone="success">Lagrad rekommendation</Badge>}</div><p className="mt-2">{amount(offer.total_price)}</p><p className="mt-1 text-xs text-zinc-500">{offer.availability ?? "Ingen lageruppgift"} · Leverans {formatDateTime(offer.delivery_at)}</p><p className="mt-1 text-xs text-zinc-400">Offert skapad {formatDateTime(offer.created_at)}{offer.valid_until ? ` · giltig till ${formatDateTime(offer.valid_until)}` : ""}</p></div>)}</div>}</article>; })}</div>
      : tab === "orders" ? <div className="mt-5 space-y-3">{!visibleOrders.length ? <Empty icon={Truck} title={data.orders.length ? "Inga order matchar sökningen." : "Inga inköpsorder är registrerade."} text="Leveranser visas först när en verklig order och leveranspost finns." /> : visibleOrders.map((order) => { const deliveries = data.deliveries.filter((delivery) => delivery.purchase_order_id === order.id); return <article key={order.id} className="rounded-2xl border border-zinc-200 p-4"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="font-semibold">Order {order.order_number} · {order.supplier_name}</h3><p className="mt-2 text-sm text-zinc-600">{projects.get(order.project_id)?.name ?? "Okänt projekt"} · {amount(order.total_amount)} · Status {order.status}</p><p className="mt-2 text-xs text-zinc-400">Uppdaterad {formatDateTime(order.updated_at)} · Godkänd {formatDateTime(order.approved_at)} · Beställd {formatDateTime(order.ordered_at)}</p></div><Badge tone={order.status === "delivered" ? "success" : "neutral"}>{order.status}</Badge></div>{deliveries.map((delivery) => <div key={delivery.id} className="mt-3 rounded-2xl bg-zinc-50 p-3 text-sm">Leveransstatus: <strong>{delivery.status}</strong> · Planerad {formatDateTime(delivery.scheduled_at)} · Levererad {formatDateTime(delivery.delivered_at)}{delivery.note ? ` · ${delivery.note}` : ""}</div>)}</article>; })}</div>
      : <PriceAndDowntime data={data} products={products} stores={stores} />}
    </Card>
  </div>;
}

function Empty({ icon: Icon, title, text }: { icon: typeof Boxes; title: string; text: string }) { return <div className="mt-5 rounded-2xl border border-dashed border-zinc-300 p-10 text-center"><Icon className="mx-auto h-8 w-8 text-zinc-400" /><p className="mt-4 font-semibold">{title}</p><p className="mt-2 text-sm text-zinc-500">{text}</p></div>; }

function PriceAndDowntime({ data, products, stores }: { data: Payload; products: Map<string, CatalogProduct>; stores: Map<string, Store> }) {
  const rows = data.orderListItems;
  const readyCalculations = data.calculations.filter((calculation) => calculation.status === "ready" && calculation.recommended_option_id);
  if (!rows.length && !data.ownPrices.length && !data.priceListItems.length && !data.shelfPrices.length && !readyCalculations.length) return <Empty icon={Warehouse} title="Inga verifierade pris- eller lagerposter finns ännu." text={data.downtimeProfiles.length ? "Stilleståndsprofil finns, men ingen färdig beräkning finns att visa." : "Ingen stilleståndsprofil eller färdig beräkning finns. Inga rekommendationer skapas i klienten."} />;
  return <div className="mt-5 space-y-5">
    {rows.map((row) => { const product = products.get(row.catalog_product_id); const own = data.ownPrices.find((price) => price.catalog_product_id === row.catalog_product_id); const contract = data.priceListItems.find((price) => price.catalog_product_id === row.catalog_product_id); const shelf = row.merchant_product_id ? data.shelfPrices.find((price) => price.merchant_product_id === row.merchant_product_id) : null; const stock = row.merchant_product_id ? data.inventory.find((entry) => entry.merchant_product_id === row.merchant_product_id && (!row.selected_store_id || entry.store_id === row.selected_store_id)) : null; return <article key={row.id} className="rounded-2xl border border-zinc-200 p-4"><h3 className="font-semibold">{product?.name ?? "Katalogprodukt"}</h3><p className="mt-1 text-sm text-zinc-500">{number.format(Number(row.quantity))} {row.unit}{product?.manufacturer ? ` · ${product.manufacturer}` : ""}</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><SourceBox label="Eget pris" value={own?.latest_invoice_price_ex_vat ?? own?.manual_cost_price_ex_vat ?? row.selected_unit_cost_ex_vat} detail={own?.latest_invoice_price_ex_vat !== null && own?.latest_invoice_price_ex_vat !== undefined ? `Leverantörsfaktura ${formatDate(own.latest_invoice_date)}` : own ? `Manuellt pris · uppdaterat ${formatDateTime(own.updated_at)}` : `Vald källa: ${row.selected_price_source ?? "saknas"}`} /><SourceBox label="Avtalspris exkl. moms" value={contract?.contract_price_ex_vat ?? null} detail={contract ? `${data.priceLists.find((list) => list.id === contract.price_list_id)?.name ?? "Prislista"} · uppdaterad ${formatDateTime(contract.updated_at)}` : "Ingen träff i egen prislista"} /><SourceBox label="Offentligt hyllpris exkl. moms" value={shelf?.price_ex_vat ?? row.shelf_price_ex_vat} detail={shelf ? `Källa: ${shelf.source_reference} · verifierad ${formatDateTime(shelf.last_verified_at)}` : "Ingen verifierad publik snapshot"} /><div className="rounded-2xl bg-zinc-50 p-3"><p className="text-xs text-zinc-500">Lager</p><p className="mt-1 font-semibold">{stock?.quantity_available !== null && stock?.quantity_available !== undefined ? `${number.format(Number(stock.quantity_available))} ${stock.quantity_unit ?? ""}` : stock?.stock_status ?? row.stock_status_at_selection ?? "Ej tillgängligt"}</p><p className="mt-1 text-xs text-zinc-400">{stock ? `${stores.get(stock.store_id)?.name ?? "Butik"} · källa ${stock.source_reference} · hämtad ${formatDateTime(stock.captured_at)}` : row.stock_checked_at ? `Kontrollerad ${formatDateTime(row.stock_checked_at)}` : "Ingen lagersnapshot"}</p></div></div></article>; })}
    {readyCalculations.map((calculation) => { const option = data.options.find((candidate) => candidate.id === calculation.recommended_option_id && candidate.recommended); if (!option) return null; return <article key={calculation.id} className="rounded-2xl bg-emerald-50 p-5"><div className="flex items-center gap-2 font-semibold text-emerald-900"><CalendarClock className="h-5 w-5" /> Färdigberäknat stilleståndsalternativ</div><p className="mt-3 text-sm text-emerald-900">{calculation.calculation_summary ?? option.reason ?? "Beräkningen har markerat detta alternativ som rekommenderat."}</p><div className="mt-4 grid gap-2 text-sm md:grid-cols-4"><span>Material {amount(option.material_cost_ex_vat)}</span><span>Stillestånd {amount(option.downtime_cost)}</span><span>Tidsrisk {amount(option.schedule_risk_cost)}</span><span>Effektiv totalkostnad {amount(option.total_effective_cost)}</span></div><p className="mt-3 text-xs text-emerald-700">Algoritm {calculation.algorithm_version} · beräknad {formatDateTime(calculation.calculated_at)} · pris kontrollerat {formatDateTime(option.price_checked_at)} · lager kontrollerat {formatDateTime(option.stock_checked_at)}</p></article>; })}
  </div>;
}

function SourceBox({ label, value, detail }: { label: string; value: number | string | null | undefined; detail: string }) { return <div className="rounded-2xl bg-zinc-50 p-3"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 font-semibold">{value === null || value === undefined ? "Ej registrerat" : amount(value)}</p><p className="mt-1 text-xs text-zinc-400">{detail}</p></div>; }
