export type ModuleId =
  | "core-flow"
  | "dashboard"
  | "projects"
  | "project-detail"
  | "people"
  | "time"
  | "payroll"
  | "foreman"
  | "site-manager"
  | "materials"
  | "connect"
  | "change-orders"
  | "quotes"
  | "settings";
