"use client";

import { type FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Cable, CheckCircle2, CircleAlert, ClipboardCheck, Eye, FileCheck2, Home, Layers3, MapPinned, Plus, RadioTower, ShieldCheck, X } from "lucide-react";
import { Badge, Card, Stat } from "@/components/ui/core";
import PortalInvitationsPanel from "@/components/modules/property/PortalInvitationsPanel";

type Project = { id: string; project_number: string; name: string; customer_name: string | null; address: string | null; postal_code: string | null; city: string | null; status: string; progress: number | string; active: boolean };
type Property = { id: string; property_number: string; name: string; property_type: string; status: string; address: string | null; postal_code: string | null; city: string | null; commissioned_on: string | null; designed_service_life_years: number; created_at: string; updated_at: string };
type PropertyLink = { id: string; project_id: string; property_id: string; relationship_type: string; is_primary: boolean; handover_status: string; handover_at: string | null; created_at: string; updated_at: string };
type PortalSettings = { id: string; project_id: string; status: string; portal_name: string | null; welcome_text: string | null; enabled: boolean; require_review_before_publish: boolean; allow_customer_comments: boolean; allow_customer_acknowledgements: boolean; share_project_progress: boolean; share_documents: boolean; share_installation_map: boolean; share_weather: boolean; share_checkins: boolean; checkin_display_mode: string; notify_on_publication: boolean; project_closed_at: string | null; included_access_until: string | null; extended_access_active: boolean; updated_at: string };
type Zone = { id: string; project_id: string; parent_zone_id: string | null; zone_code: string; name: string; zone_type: string; description: string | null; status: string; sort_order: number; created_at: string; updated_at: string };
type Installation = { id: string; project_id: string; zone_id: string | null; installation_number: string; system_type: string; name: string; customer_description: string | null; manufacturer: string | null; product_name: string | null; model: string | null; serial_number: string | null; installed_on: string | null; concealed: boolean; expected_service_life_years: number | null; status: string; portal_visibility: string; verified_at: string | null; created_at: string; updated_at: string };
type Route = { id: string; project_id: string; installation_id: string; zone_id: string | null; route_number: string; version: number; route_kind: string; coordinate_system: string; path_points: Array<Record<string, number>>; location_description: string; depth_mm: number | string | null; height_mm: number | string | null; accuracy_mm: number | string | null; capture_method: string; status: string; portal_visibility: string; verified_at: string | null; created_at: string; updated_at: string };
type Evidence = { id: string; project_id: string; installation_id: string; route_id: string | null; project_document_evidence_id: string; portal_visibility: string; caption: string | null; sort_order: number; created_at: string };
type SourceEvidence = { id: string; project_id: string; evidence_type: string; caption: string | null; captured_at: string; verifiedFile: boolean };
type Publication = { id: string; project_id: string; source_type: string; source_key: string | null; source_version: string | null; title: string; summary: string; occurred_at: string; status: string; audience_roles: string[]; requires_acknowledgement: boolean; prepared_by: string; reviewed_at: string | null; published_at: string | null; withdrawn_at: string | null; withdrawal_reason: string | null; created_at: string; updated_at: string };
type Permissions = { canManageContent: boolean; canManageProperties: boolean; canManageSettings: boolean };
type Payload = { projects?: Project[]; properties?: Property[]; links?: PropertyLink[]; settings?: PortalSettings[]; zones?: Zone[]; installations?: Installation[]; routes?: Route[]; evidence?: Evidence[]; sourceEvidence?: SourceEvidence[]; publications?: Publication[]; permissions?: Permissions; error?: string };
type Panel = "none" | "property" | "link" | "zone" | "installation" | "route" | "evidence" | "publication";

const dateTime = new Intl.DateTimeFormat("sv-SE", { dateStyle: "medium", timeStyle: "short" });
const relationshipLabel: Record<string, string> = { new_build: "Nybyggnad", extension: "Tillbyggnad", renovation: "Renovering", maintenance: "Underhåll", inspection: "Inspektion", other: "Övrigt" };
const installationStatus: Record<string, string> = { planned: "Planerad", installed: "Installerad", verified: "Verifierad", handed_over: "Överlämnad", decommissioned: "Ur drift", superseded: "Ersatt" };
const publicationStatus: Record<string, string> = { draft: "Utkast", review: "Väntar på granskning", published: "Publicerad", withdrawn: "Tillbakadragen", superseded: "Ersatt" };
const visibilityLabel: Record<string, string> = { internal: "Internt", review: "Granskas", approved_for_portal: "Godkänt för portal" };
const systemLabel: Record<string, string> = { electrical: "El", data: "Data", water: "Vatten", wastewater: "Avlopp", stormwater: "Dagvatten", heating: "Värme", cooling: "Kyla", ventilation: "Ventilation", fire: "Brand", gas: "Gas", security: "Säkerhet", structural: "Konstruktion", ground: "Mark", other: "Övrigt" };

function tone(value: string): "neutral" | "success" | "warning" | "dark" {
  if (["verified", "handed_over", "published", "approved_for_portal", "active"].includes(value)) return "success";
  if (["review", "installed", "planning", "construction"].includes(value)) return "warning";
  if (["withdrawn", "decommissioned", "superseded"].includes(value)) return "dark";
  return "neutral";
}

export default function LivePropertyPortalModule({ notify }: { notify: (message: string) => void }) {
  const [payload, setPayload] = useState<Payload>({});
  const [selectedProjectId, setSelectedProjectId] = useState("");
  const [tab, setTab] = useState<"property" | "relations" | "portal">("property");
  const [panel, setPanel] = useState<Panel>("none");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    const response = await fetch("/api/private/property-portal", { cache: "no-store" });
    const next = (await response.json().catch(() => null)) as Payload | null;
    if (!response.ok) setError(next?.error ?? "Fastighetsunderlaget kunde inte hämtas.");
    else {
      setPayload(next ?? {});
      setSelectedProjectId((current) => current || next?.projects?.[0]?.id || "");
      setError(null);
    }
    setLoading(false);
  }, []);

  useEffect(() => { const frame = window.requestAnimationFrame(() => void load()); return () => window.cancelAnimationFrame(frame); }, [load]);

  const projects = payload.projects ?? [];
  const selectedProject = projects.find((project) => project.id === selectedProjectId) ?? null;
  const properties = useMemo(() => payload.properties ?? [], [payload.properties]);
  const projectLinks = useMemo(() => (payload.links ?? []).filter((item) => item.project_id === selectedProjectId), [payload.links, selectedProjectId]);
  const linkedProperties = useMemo(() => projectLinks.map((link) => ({ link, property: properties.find((item) => item.id === link.property_id) })).filter((item): item is { link: PropertyLink; property: Property } => Boolean(item.property)), [projectLinks, properties]);
  const projectSettings = (payload.settings ?? []).find((item) => item.project_id === selectedProjectId) ?? null;
  const projectZones = useMemo(() => (payload.zones ?? []).filter((item) => item.project_id === selectedProjectId), [payload.zones, selectedProjectId]);
  const projectInstallations = useMemo(() => (payload.installations ?? []).filter((item) => item.project_id === selectedProjectId), [payload.installations, selectedProjectId]);
  const projectRoutes = useMemo(() => (payload.routes ?? []).filter((item) => item.project_id === selectedProjectId), [payload.routes, selectedProjectId]);
  const projectEvidence = useMemo(() => (payload.evidence ?? []).filter((item) => item.project_id === selectedProjectId), [payload.evidence, selectedProjectId]);
  const sourceEvidence = useMemo(() => (payload.sourceEvidence ?? []).filter((item) => item.project_id === selectedProjectId && item.verifiedFile), [payload.sourceEvidence, selectedProjectId]);
  const publications = useMemo(() => (payload.publications ?? []).filter((item) => item.project_id === selectedProjectId), [payload.publications, selectedProjectId]);
  const permissions = payload.permissions ?? { canManageContent: false, canManageProperties: false, canManageSettings: false };

  async function mutate(method: "POST" | "PATCH", body: Record<string, unknown>, message: string) {
    setSaving(true);
    setError(null);
    const response = await fetch("/api/private/property-portal", { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
    const result = (await response.json().catch(() => null)) as { error?: string } | null;
    if (!response.ok) {
      setError(result?.error ?? "Åtgärden kunde inte genomföras.");
      setSaving(false);
      return false;
    }
    notify(message);
    setPanel("none");
    await load();
    setSaving(false);
    return true;
  }

  function formValues(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const values = Object.fromEntries(new FormData(form));
    return { form, values };
  }

  if (loading) return <Card className="p-12 text-center text-zinc-500">Hämtar fastigheter och kundportal…</Card>;

  return <div className="space-y-5">
    <Card className="flex flex-col justify-between gap-6 bg-zinc-950 p-7 text-white lg:flex-row lg:items-end">
      <div><Badge tone="success">Från projekt till 100 års förvaltning</Badge><h2 className="mt-5 text-4xl font-semibold tracking-tight">Fastighet & kundportal</h2><p className="mt-3 max-w-3xl text-zinc-300">Projektets verifierade rum, installationer, sträckningar och bevis följer med till fastigheten. Kunden ser bara material som har granskats och publicerats.</p></div>
      <label className="min-w-72 text-sm"><span className="mb-2 block text-zinc-300">Aktivt projekt</span><select value={selectedProjectId} onChange={(event) => { setSelectedProjectId(event.target.value); setPanel("none"); }} className="w-full rounded-2xl border border-white/20 bg-white px-4 py-3 font-semibold text-zinc-950"><option value="">Välj projekt</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.project_number} · {project.name}</option>)}</select></label>
    </Card>

    {error && <p className="rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    {!selectedProject ? <Card className="p-12 text-center text-zinc-500">Företaget har inget projekt att bygga ett relationsunderlag för ännu.</Card> : <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Building2} label="Fastigheter" value={String(linkedProperties.length)} helper="Kopplade till projektet" /><Stat icon={Layers3} label="Zoner och rum" value={String(projectZones.length)} helper="Strukturerade platser" /><Stat icon={Cable} label="Installationer" value={String(projectInstallations.length)} helper={`${projectRoutes.length} dokumenterade sträckningar`} /><Stat icon={RadioTower} label="Publicerat" value={String(publications.filter((item) => item.status === "published").length)} helper={`${publications.filter((item) => item.status === "review").length} väntar på granskning`} /></div>
      <div className="flex gap-2 overflow-x-auto rounded-2xl bg-zinc-100 p-1.5">{([{ id: "property", label: "Fastigheten", icon: Home }, { id: "relations", label: "Relationsunderlag", icon: MapPinned }, { id: "portal", label: "Kundportal", icon: Eye }] as const).map((item) => <button key={item.id} onClick={() => { setTab(item.id); setPanel("none"); }} className={`inline-flex items-center gap-2 whitespace-nowrap rounded-xl px-4 py-3 text-sm font-semibold ${tab === item.id ? "bg-white text-zinc-950 shadow-sm" : "text-zinc-500"}`}><item.icon className="h-4 w-4" />{item.label}</button>)}</div>

      {tab === "property" && <PropertySection selectedProject={selectedProject} properties={properties} linkedProperties={linkedProperties} permissions={permissions} panel={panel} saving={saving} setPanel={setPanel} submit={(event, action, message) => { const { values } = formValues(event); void mutate("POST", { action, projectId: selectedProjectId, ...values }, message); }} />}
      {tab === "relations" && <RelationsSection projectId={selectedProjectId} zones={projectZones} installations={projectInstallations} routes={projectRoutes} evidence={projectEvidence} sourceEvidence={sourceEvidence} panel={panel} saving={saving} setPanel={setPanel} submit={(event, action, message) => { const { values } = formValues(event); void mutate("POST", { action, projectId: selectedProjectId, ...values, concealed: values.concealed === "on" }, message); }} act={(action, values, message) => void mutate("PATCH", { action, ...values }, message)} />}
      {tab === "portal" && <PortalSection projectId={selectedProjectId} projectName={selectedProject.name} settings={projectSettings} publications={publications} permissions={permissions} panel={panel} saving={saving} setPanel={setPanel} submitPublication={(event) => { const { form, values } = formValues(event); const audienceRoles = Array.from(form.querySelectorAll<HTMLInputElement>('input[name="audience"]:checked')).map((input) => input.value); void mutate("POST", { action: "create_publication", projectId: selectedProjectId, ...values, audienceRoles, requiresAcknowledgement: values.requiresAcknowledgement === "on" }, "Portalposten sparades för granskning"); }} saveSettings={(event) => { const { form, values } = formValues(event); const checked = (name: string) => Boolean(form.querySelector<HTMLInputElement>(`input[name="${name}"]`)?.checked); void mutate("PATCH", { action: "update_settings", projectId: selectedProjectId, ...values, enabled: checked("enabled"), allowCustomerComments: checked("allowCustomerComments"), allowCustomerAcknowledgements: checked("allowCustomerAcknowledgements"), shareProjectProgress: checked("shareProjectProgress"), shareDocuments: checked("shareDocuments"), shareInstallationMap: checked("shareInstallationMap"), shareWeather: checked("shareWeather"), shareCheckins: checked("shareCheckins"), notifyOnPublication: checked("notifyOnPublication") }, "Kundportalens inställningar sparades"); }} act={(action, values, message) => void mutate("PATCH", { action, ...values }, message)} notify={notify} />}
    </>}
  </div>;
}

function PropertySection({ selectedProject, properties, linkedProperties, permissions, panel, saving, setPanel, submit }: { selectedProject: Project; properties: Property[]; linkedProperties: Array<{ link: PropertyLink; property: Property }>; permissions: Permissions; panel: Panel; saving: boolean; setPanel: (panel: Panel) => void; submit: (event: FormEvent<HTMLFormElement>, action: string, message: string) => void }) {
  const unlinked = properties.filter((property) => !linkedProperties.some((item) => item.property.id === property.id));
  return <div className="grid gap-5 xl:grid-cols-[1fr_380px]">
    <Card className="p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-xl font-semibold">Projektets fastighet</h3><p className="mt-1 text-sm text-zinc-500">{selectedProject.address ? `${selectedProject.address}, ${selectedProject.postal_code ?? ""} ${selectedProject.city ?? ""}` : "Projektadress är inte registrerad."}</p></div>{permissions.canManageProperties && <div className="flex gap-2"><button onClick={() => setPanel("property")} className="rounded-xl bg-zinc-950 px-4 py-2 text-sm font-semibold text-white"><Plus className="mr-2 inline h-4 w-4" />Ny fastighet</button>{unlinked.length > 0 && <button onClick={() => setPanel("link")} className="rounded-xl border border-zinc-300 px-4 py-2 text-sm font-semibold">Koppla befintlig</button>}</div>}</div>
      <div className="mt-6 space-y-3">{linkedProperties.length === 0 ? <p className="rounded-2xl border border-dashed border-zinc-300 p-10 text-center text-zinc-500">Projektet är ännu inte kopplat till en fastighet.</p> : linkedProperties.map(({ link, property }) => <div key={link.id} className="rounded-2xl border border-zinc-200 p-5"><div className="flex flex-wrap items-center gap-2"><h4 className="font-semibold">{property.name}</h4><Badge tone={tone(property.status)}>{property.status}</Badge><Badge>{relationshipLabel[link.relationship_type] ?? link.relationship_type}</Badge></div><p className="mt-2 text-sm text-zinc-500">{property.property_number} · {[property.address, property.postal_code, property.city].filter(Boolean).join(", ") || "Adress saknas"}</p><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div><p className="text-zinc-500">Planerad livslängd</p><p className="font-semibold">{property.designed_service_life_years} år</p></div><div><p className="text-zinc-500">Överlämning</p><p className="font-semibold">{link.handover_status}</p></div><div><p className="text-zinc-500">Driftsatt</p><p className="font-semibold">{property.commissioned_on ?? "Inte ännu"}</p></div></div></div>)}</div>
    </Card>
    <Card className="p-6"><h3 className="font-semibold">Digitalt fastighetsminne</h3><div className="mt-5 space-y-4 text-sm text-zinc-600"><Info icon={MapPinned} title="Rätt plats" text="Varje installation kopplas till projekt, byggnadsdel och rum." /><Info icon={FileCheck2} title="Verifierad verklighet" text="Sträckningar och bevis låses efter verifiering." /><Info icon={ShieldCheck} title="Granskad kundversion" text="Interna anteckningar följer aldrig med till kundportalen." /></div></Card>
    {panel === "property" && <FormDrawer title="Ny fastighet" saving={saving} setPanel={setPanel}><form onSubmit={(event) => submit(event, "create_property", "Fastigheten registrerades")} className="space-y-4"><Field name="propertyNumber" label="Fastighetsnummer *" required /><Field name="name" label="Namn *" required /><Select name="propertyType" label="Typ *" options={[['single_family','Villa'],['multi_family','Flerbostadshus'],['commercial','Kommersiell'],['industrial','Industri'],['public','Offentlig'],['sports_facility','Idrottsanläggning'],['land','Mark'],['infrastructure','Infrastruktur'],['other','Övrigt']]} /><Field name="address" label="Adress" /><div className="grid grid-cols-2 gap-3"><Field name="postalCode" label="Postnummer" /><Field name="city" label="Ort" /></div><Field name="designedServiceLifeYears" label="Planerad livslängd, år *" type="number" defaultValue="100" required /><Submit saving={saving} label="Registrera fastighet" /></form></FormDrawer>}
    {panel === "link" && <FormDrawer title="Koppla fastighet" saving={saving} setPanel={setPanel}><form onSubmit={(event) => submit(event, "link_property", "Fastigheten kopplades till projektet")} className="space-y-4"><Select name="propertyId" label="Fastighet *" options={unlinked.map((item) => [item.id, `${item.property_number} · ${item.name}`])} /><Select name="relationshipType" label="Projektets relation *" options={Object.entries(relationshipLabel)} /><Submit saving={saving} label="Koppla fastighet" /></form></FormDrawer>}
  </div>;
}

function RelationsSection({ projectId, zones, installations, routes, evidence, sourceEvidence, panel, saving, setPanel, submit, act }: { projectId: string; zones: Zone[]; installations: Installation[]; routes: Route[]; evidence: Evidence[]; sourceEvidence: SourceEvidence[]; panel: Panel; saving: boolean; setPanel: (panel: Panel) => void; submit: (event: FormEvent<HTMLFormElement>, action: string, message: string) => void; act: (action: string, values: Record<string, unknown>, message: string) => void }) {
  return <div className="space-y-5">
    <Card className="p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h3 className="text-xl font-semibold">Byggnad, zon och rum</h3><p className="mt-1 text-sm text-zinc-500">En gemensam platsstruktur för dokumentation och framtida förvaltning.</p></div><button onClick={() => setPanel("zone")} className="rounded-xl bg-zinc-950 px-4 py-2 text-sm font-semibold text-white"><Plus className="mr-2 inline h-4 w-4" />Ny zon</button></div><div className="mt-5 flex flex-wrap gap-2">{zones.length === 0 ? <p className="w-full rounded-2xl border border-dashed border-zinc-300 p-8 text-center text-zinc-500">Inga zoner eller rum har registrerats.</p> : zones.map((zone) => <span key={zone.id} className="rounded-xl border border-zinc-200 px-3 py-2 text-sm"><span className="font-semibold">{zone.zone_code}</span> · {zone.name}<span className="ml-2 text-zinc-400">{zone.zone_type}</span></span>)}</div></Card>
    <Card className="p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h3 className="text-xl font-semibold">Installationer och dolda sträckningar</h3><p className="mt-1 text-sm text-zinc-500">Verifiering låser det tekniska innehållet. En portalversion förbereds först efter godkännande.</p></div><button onClick={() => setPanel("installation")} disabled={zones.length === 0} className="rounded-xl bg-zinc-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40"><Plus className="mr-2 inline h-4 w-4" />Ny installation</button></div>
      <div className="mt-6 space-y-4">{installations.length === 0 ? <p className="rounded-2xl border border-dashed border-zinc-300 p-10 text-center text-zinc-500">Skapa först en zon och därefter projektets första verkliga installation.</p> : installations.map((installation) => { const zone = zones.find((item) => item.id === installation.zone_id); const installationRoutes = routes.filter((item) => item.installation_id === installation.id); const installationEvidence = evidence.filter((item) => item.installation_id === installation.id); const verifiedRoute = installationRoutes.some((item) => item.status === "verified" && item.portal_visibility === "approved_for_portal"); return <div key={installation.id} className="rounded-2xl border border-zinc-200 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h4 className="font-semibold">{installation.installation_number} · {installation.name}</h4><Badge tone={tone(installation.status)}>{installationStatus[installation.status] ?? installation.status}</Badge><Badge tone={tone(installation.portal_visibility)}>{visibilityLabel[installation.portal_visibility] ?? installation.portal_visibility}</Badge>{installation.concealed && <Badge tone="warning">Dold installation</Badge>}</div><p className="mt-2 text-sm text-zinc-500">{systemLabel[installation.system_type] ?? installation.system_type} · {zone ? `${zone.zone_code} ${zone.name}` : "Zon saknas"}</p>{installation.customer_description && <p className="mt-3 text-sm text-zinc-700">{installation.customer_description}</p>}</div><div className="flex flex-wrap gap-2">{installation.status === "planned" && <Action saving={saving} onClick={() => act("mark_installed", { installationId: installation.id }, `${installation.name} markerades som installerad`)}>Markera installerad</Action>}<Action saving={saving} onClick={() => { setPanel("route"); sessionStorage.setItem("bynex-installation", installation.id); }}>Ny sträckning</Action>{sourceEvidence.length > 0 && <Action saving={saving} onClick={() => { setPanel("evidence"); sessionStorage.setItem("bynex-installation", installation.id); }}>Koppla bevis</Action>}{installation.status === "installed" && verifiedRoute && <Action saving={saving} onClick={() => act("approve_installation", { installationId: installation.id }, `${installation.name} godkändes för portalen`)}>Godkänn installation</Action>}{installation.status === "verified" && installation.portal_visibility === "approved_for_portal" && <Action saving={saving} onClick={() => act("prepare_installation", { installationId: installation.id }, "Installationen förbereddes som granskad portalpost")}>Förbered portalpost</Action>}</div></div>
          <div className="mt-5 grid gap-3 lg:grid-cols-2"><div className="rounded-xl bg-zinc-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Sträckningar</p>{installationRoutes.length === 0 ? <p className="mt-3 text-sm text-zinc-500">Ingen sträckning dokumenterad.</p> : installationRoutes.map((route) => <div key={route.id} className="mt-3 border-t border-zinc-200 pt-3 first:border-0 first:pt-0"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold">{route.route_number} · version {route.version}</p><p className="mt-1 text-xs text-zinc-500">{route.location_description} · {route.path_points.length} punkter</p></div>{route.status === "draft" ? <Action saving={saving} onClick={() => act("verify_route", { routeId: route.id }, `${route.route_number} verifierades och godkändes`)}>Verifiera</Action> : <Badge tone="success">Verifierad</Badge>}</div></div>)}</div><div className="rounded-xl bg-zinc-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Bevis</p>{installationEvidence.length === 0 ? <p className="mt-3 text-sm text-zinc-500">Inga filbevis kopplade.</p> : installationEvidence.map((item) => <div key={item.id} className="mt-3 flex items-center justify-between gap-3 border-t border-zinc-200 pt-3 first:border-0 first:pt-0"><div><p className="text-sm font-semibold">{item.caption || "Dokumentationsbevis"}</p><p className="mt-1 text-xs text-zinc-500">{visibilityLabel[item.portal_visibility] ?? item.portal_visibility}</p></div>{item.portal_visibility === "review" && <Action saving={saving} onClick={() => act("approve_evidence", { evidenceId: item.id }, "Beviset godkändes för kundportalen")}>Godkänn</Action>}</div>)}</div></div>
        </div>; })}</div>
    </Card>
    {panel === "zone" && <FormDrawer title="Ny zon eller rum" saving={saving} setPanel={setPanel}><form onSubmit={(event) => submit(event, "create_zone", "Zonen skapades")} className="space-y-4"><Field name="zoneCode" label="Kod *" required /><Field name="name" label="Namn *" required /><Select name="zoneType" label="Typ *" options={[['site','Arbetsplats'],['ground','Mark'],['building','Byggnad'],['level','Våningsplan'],['unit','Enhet'],['room','Rum'],['shaft','Schakt'],['area','Område'],['exterior','Utvändigt'],['other','Övrigt']]} /><Select name="parentZoneId" label="Överordnad zon" optional options={zones.map((item) => [item.id, `${item.zone_code} · ${item.name}`])} /><Field name="description" label="Beskrivning" multiline /><Submit saving={saving} label="Skapa zon" /></form></FormDrawer>}
    {panel === "installation" && <FormDrawer title="Ny installation" saving={saving} setPanel={setPanel}><form onSubmit={(event) => submit(event, "create_installation", "Installationen skapades")} className="space-y-4"><Select name="zoneId" label="Zon eller rum *" options={zones.map((item) => [item.id, `${item.zone_code} · ${item.name}`])} /><Field name="installationNumber" label="Installationsnummer *" required /><Field name="name" label="Namn *" required /><Select name="systemType" label="System *" options={Object.entries(systemLabel)} /><Field name="customerDescription" label="Beskrivning för relationsunderlaget" multiline /><div className="grid grid-cols-2 gap-3"><Field name="manufacturer" label="Tillverkare" /><Field name="productName" label="Produkt" /><Field name="model" label="Modell" /><Field name="serialNumber" label="Serienummer" /></div><Field name="expectedServiceLifeYears" label="Förväntad livslängd, år" type="number" /><label className="flex items-center gap-3 rounded-xl bg-zinc-50 p-4 text-sm"><input name="concealed" type="checkbox" className="h-4 w-4" />Installationen byggs in eller döljs</label><Submit saving={saving} label="Skapa installation" /></form></FormDrawer>}
    {panel === "route" && <FormDrawer title="Dokumentera sträckning" saving={saving} setPanel={setPanel}><RouteForm projectId={projectId} installations={installations} zones={zones} saving={saving} submit={submit} /></FormDrawer>}
    {panel === "evidence" && <FormDrawer title="Koppla verifierat bevis" saving={saving} setPanel={setPanel}><EvidenceForm installations={installations} routes={routes} sourceEvidence={sourceEvidence} saving={saving} submit={submit} /></FormDrawer>}
  </div>;
}

function PortalSection({ projectId, projectName, settings, publications, permissions, panel, saving, setPanel, submitPublication, saveSettings, act, notify }: { projectId: string; projectName: string; settings: PortalSettings | null; publications: Publication[]; permissions: Permissions; panel: Panel; saving: boolean; setPanel: (panel: Panel) => void; submitPublication: (event: FormEvent<HTMLFormElement>) => void; saveSettings: (event: FormEvent<HTMLFormElement>) => void; act: (action: string, values: Record<string, unknown>, message: string) => void; notify: (message: string) => void }) {
  const accessLabel = settings?.extended_access_active
    ? "Digitalpärmen fortsätter"
    : settings?.included_access_until
      ? `Den inkluderade åtkomsten gäller till ${new Date(settings.included_access_until).toLocaleDateString("sv-SE")}`
      : "Ingår under projektet och i 12 månader efter avslut";
  return <div className="grid gap-5 xl:grid-cols-[390px_1fr]">
    {settings && <Card className="bg-emerald-50 p-5 xl:col-span-2"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-800" /><div><p className="font-semibold">{accessLabel}</p><p className="mt-1 text-sm leading-6 text-zinc-700">Efter den inkluderade tiden kan kunden behålla ritningar, garantier och projekthistorik i Bynex Digitalpärm för 19 kr/mån eller 190 kr/år inklusive moms per fastighet.</p></div></div></Card>}
    <PortalInvitationsPanel projectId={projectId} projectName={projectName} enabled={settings?.enabled === true} notify={notify} />
    <Card className="p-6"><div className="flex items-center justify-between gap-3"><div><h3 className="text-xl font-semibold">Portalinställningar</h3><p className="mt-1 text-sm text-zinc-500">Företaget bestämmer exakt vad kunden får se.</p></div>{settings && <Badge tone={settings.enabled ? "success" : "neutral"}>{settings.enabled ? "Aktiv" : "Avstängd"}</Badge>}</div>{!settings ? <p className="mt-6 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">Projektets portalinställning saknas. Den ska skapas automatiskt tillsammans med ett projekt.</p> : <form key={settings.updated_at} onSubmit={saveSettings} className="mt-6 space-y-4"><Field name="portalName" label="Portalnamn" defaultValue={settings.portal_name ?? ""} /><Field name="welcomeText" label="Välkomsttext" defaultValue={settings.welcome_text ?? ""} multiline /><Toggle name="enabled" label="Portalen är aktiv" defaultChecked={settings.enabled} disabled={!permissions.canManageSettings} /><Toggle name="shareProjectProgress" label="Visa projektets framdrift" defaultChecked={settings.share_project_progress} disabled={!permissions.canManageSettings} /><Toggle name="shareDocuments" label="Visa publicerade dokument" defaultChecked={settings.share_documents} disabled={!permissions.canManageSettings} /><Toggle name="shareInstallationMap" label="Visa verifierade installationer" defaultChecked={settings.share_installation_map} disabled={!permissions.canManageSettings} /><Toggle name="shareWeather" label="Visa väderhistorik" defaultChecked={settings.share_weather} disabled={!permissions.canManageSettings} /><Toggle name="shareCheckins" label="Visa in-/utcheckningar" defaultChecked={settings.share_checkins} disabled={!permissions.canManageSettings} /><Select name="checkinDisplayMode" label="Visning av incheckning" defaultValue={settings.checkin_display_mode} options={[['aggregate','Endast antal'],['named','Namn och tider']]} /><Toggle name="allowCustomerComments" label="Tillåt kundkommentarer" defaultChecked={settings.allow_customer_comments} disabled={!permissions.canManageSettings} /><Toggle name="allowCustomerAcknowledgements" label="Tillåt kvittens" defaultChecked={settings.allow_customer_acknowledgements} disabled={!permissions.canManageSettings} /><Toggle name="notifyOnPublication" label="Avisera vid publicering" defaultChecked={settings.notify_on_publication} disabled={!permissions.canManageSettings} /><div className="flex items-start gap-3 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" /><p>Granskning före publicering är alltid aktiverad och kan inte stängas av.</p></div>{permissions.canManageSettings && <Submit saving={saving} label="Spara portalinställningar" />}</form>}</Card>
    <Card className="p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-xl font-semibold">Granskad tidslinje</h3><p className="mt-1 text-sm text-zinc-500">Kunden läser en separat publicerad version, aldrig företagets interna original.</p></div><button onClick={() => setPanel("publication")} disabled={!settings?.enabled} className="rounded-xl bg-zinc-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40"><Plus className="mr-2 inline h-4 w-4" />Ny portalpost</button></div>
      <div className="mt-6 space-y-3">{publications.length === 0 ? <p className="rounded-2xl border border-dashed border-zinc-300 p-10 text-center text-zinc-500">Inget har publicerats eller lagts för granskning ännu.</p> : publications.map((publication) => <div key={publication.id} className="rounded-2xl border border-zinc-200 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h4 className="font-semibold">{publication.title}</h4><Badge tone={tone(publication.status)}>{publicationStatus[publication.status] ?? publication.status}</Badge>{publication.requires_acknowledgement && <Badge tone="warning">Kvittens krävs</Badge>}</div><p className="mt-2 text-sm text-zinc-600">{publication.summary}</p><p className="mt-3 text-xs text-zinc-400">{dateTime.format(new Date(publication.occurred_at))} · {publication.prepared_by === "bynex_smart" ? "Förberedd av Bynex Smart" : "Förberedd av användare"}</p></div><div className="flex gap-2">{publication.status === "review" && <Action saving={saving} onClick={() => act("publish_publication", { publicationId: publication.id }, `${publication.title} publicerades`)}>Granska och publicera</Action>}{publication.status === "published" && <Action saving={saving} onClick={() => { const reason = window.prompt("Ange skälet till att portalposten dras tillbaka:"); if (reason) act("withdraw_publication", { publicationId: publication.id, reason }, `${publication.title} drogs tillbaka`); }}>Dra tillbaka</Action>}</div></div></div>)}</div>
    </Card>
    {panel === "publication" && <FormDrawer title="Ny granskad portalpost" saving={saving} setPanel={setPanel}><form onSubmit={submitPublication} className="space-y-4"><input type="hidden" name="projectId" value={projectId} /><Select name="sourceType" label="Typ *" options={[['announcement','Meddelande'],['milestone','Milstolpe'],['photo','Bild'],['document','Dokument'],['drawing','Ritning'],['change_order','ÄTA'],['delivery','Leverans'],['deviation','Avvikelse'],['warranty','Garanti'],['inspection','Kontroll'],['weather','Väder'],['handover','Överlämning']]} /><Field name="title" label="Rubrik *" required /><Field name="summary" label="Sammanfattning *" required multiline /><Field name="details" label="Detaljer för kunden" multiline /><fieldset><legend className="text-sm font-semibold">Mottagare *</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{[['customer_owner','Beställare'],['customer_contact','Kundkontakt'],['architect','Arkitekt'],['engineer','Konstruktör'],['inspector','Besiktningsman'],['property_manager','Förvaltare'],['tenant','Hyresgäst']].map(([value,label], index) => <label key={value} className="flex items-center gap-2 rounded-xl bg-zinc-50 p-3 text-sm"><input name="audience" type="checkbox" value={value} defaultChecked={index < 2} />{label}</label>)}</div></fieldset><label className="flex items-center gap-3 rounded-xl bg-zinc-50 p-4 text-sm"><input name="requiresAcknowledgement" type="checkbox" />Kunden måste kvittera posten</label><div className="flex items-start gap-3 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><ClipboardCheck className="mt-0.5 h-5 w-5 shrink-0" /><p>Posten sparas först för mänsklig granskning. Publicering sker i ett separat låst steg.</p></div><Submit saving={saving} label="Spara för granskning" /></form></FormDrawer>}
  </div>;
}

function RouteForm({ projectId, installations, zones, saving, submit }: { projectId: string; installations: Installation[]; zones: Zone[]; saving: boolean; submit: (event: FormEvent<HTMLFormElement>, action: string, message: string) => void }) {
  const initial = typeof window !== "undefined" ? sessionStorage.getItem("bynex-installation") ?? "" : "";
  return <form onSubmit={(event) => submit(event, "create_route", "Installationssträckan skapades som utkast")} className="space-y-4"><input type="hidden" name="projectId" value={projectId} /><Select name="installationId" label="Installation *" defaultValue={initial} options={installations.map((item) => [item.id, `${item.installation_number} · ${item.name}`])} /><Select name="zoneId" label="Zon" optional options={zones.map((item) => [item.id, `${item.zone_code} · ${item.name}`])} /><Field name="routeNumber" label="Sträckningsnummer *" required /><Field name="locationDescription" label="Platsbeskrivning *" required multiline /><Field name="pathPoints" label="Koordinater i lokalt rutnät *" placeholder="0,0; 1250,0; 1250,840" required /><p className="-mt-2 text-xs text-zinc-500">Ange en eller flera punkter som x,y separerade med semikolon. Måtten följer projektets lokala ritningsrutnät.</p><div className="grid grid-cols-3 gap-3"><Field name="depthMm" label="Djup mm" type="number" /><Field name="heightMm" label="Höjd mm" type="number" /><Field name="accuracyMm" label="Noggrannhet mm" type="number" /></div><div className="flex items-start gap-3 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0" /><p>Kontrollera punkterna på rätt ritning innan sträckningen verifieras. Verifierat innehåll låses.</p></div><Submit saving={saving} label="Spara sträckning som utkast" /></form>;
}

function EvidenceForm({ installations, routes, sourceEvidence, saving, submit }: { installations: Installation[]; routes: Route[]; sourceEvidence: SourceEvidence[]; saving: boolean; submit: (event: FormEvent<HTMLFormElement>, action: string, message: string) => void }) {
  const initial = typeof window !== "undefined" ? sessionStorage.getItem("bynex-installation") ?? "" : "";
  return <form onSubmit={(event) => submit(event, "attach_evidence", "Det verifierade filunderlaget kopplades till installationen")} className="space-y-4"><Select name="installationId" label="Installation *" defaultValue={initial} options={installations.map((item) => [item.id, `${item.installation_number} · ${item.name}`])} /><Select name="routeId" label="Sträckning" optional options={routes.map((item) => [item.id, `${item.route_number} · ${item.location_description}`])} /><Select name="sourceEvidenceId" label="Verifierat dokumentationsbevis *" options={sourceEvidence.map((item) => [item.id, `${item.evidence_type} · ${item.caption || new Date(item.captured_at).toLocaleDateString("sv-SE")}`])} /><Field name="caption" label="Kundvänlig bildtext" /><div className="flex items-start gap-3 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0" /><p>Endast filer med lagringsreferens och kontrollsumma kan kopplas. Beviset måste sedan godkännas innan kunden kan se det.</p></div><Submit saving={saving} label="Koppla bevis för granskning" /></form>;
}

function FormDrawer({ title, saving, setPanel, children }: { title: string; saving: boolean; setPanel: (panel: Panel) => void; children: React.ReactNode }) {
  return <div className="fixed inset-0 z-[70] flex justify-end bg-black/35"><div className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-center justify-between gap-4"><h2 className="text-3xl font-semibold">{title}</h2><button type="button" onClick={() => setPanel("none")} disabled={saving} aria-label="Stäng" className="rounded-xl p-2 hover:bg-zinc-100"><X className="h-5 w-5" /></button></div><div className="mt-7">{children}</div></div></div>;
}

function Field({ name, label, type = "text", defaultValue, required, multiline, placeholder }: { name: string; label: string; type?: string; defaultValue?: string; required?: boolean; multiline?: boolean; placeholder?: string }) {
  return <label className="block"><span className="text-sm font-semibold">{label}</span>{multiline ? <textarea name={name} defaultValue={defaultValue} required={required} maxLength={4000} rows={4} placeholder={placeholder} className="input mt-2 min-h-28" /> : <input name={name} type={type} defaultValue={defaultValue} required={required} maxLength={type === "number" ? undefined : 300} placeholder={placeholder} className="input mt-2" />}</label>;
}

function Select({ name, label, options, optional, defaultValue }: { name: string; label: string; options: Array<readonly [string, string]>; optional?: boolean; defaultValue?: string }) {
  return <label className="block"><span className="text-sm font-semibold">{label}</span><select name={name} required={!optional} defaultValue={defaultValue ?? ""} className="input mt-2"><option value="">{optional ? "Ingen" : "Välj"}</option>{options.map(([value, optionLabel]) => <option key={value} value={value}>{optionLabel}</option>)}</select></label>;
}

function Toggle({ name, label, defaultChecked, disabled }: { name: string; label: string; defaultChecked: boolean; disabled?: boolean }) {
  return <label className="flex items-center justify-between gap-4 rounded-xl bg-zinc-50 p-4 text-sm"><span>{label}</span><input name={name} type="checkbox" defaultChecked={defaultChecked} disabled={disabled} className="h-4 w-4" /></label>;
}

function Submit({ saving, label }: { saving: boolean; label: string }) {
  return <button disabled={saving} className="w-full rounded-2xl bg-zinc-950 px-5 py-4 font-semibold text-white disabled:opacity-50">{saving ? "Sparar…" : label}</button>;
}

function Action({ saving, onClick, children }: { saving: boolean; onClick: () => void; children: React.ReactNode }) {
  return <button type="button" disabled={saving} onClick={onClick} className="rounded-xl border border-zinc-300 bg-white px-3 py-2 text-xs font-semibold text-zinc-800 hover:border-zinc-500 disabled:opacity-40">{children}</button>;
}

function Info({ icon: Icon, title, text }: { icon: typeof ShieldCheck; title: string; text: string }) {
  return <div className="flex gap-3"><span className="rounded-xl bg-zinc-100 p-2"><Icon className="h-5 w-5 text-zinc-700" /></span><div><p className="font-semibold text-zinc-900">{title}</p><p className="mt-1">{text}</p></div></div>;
}
